INV_PHYSICS_DELTA_TIME :: 1.0 / PHYSICS_DELTA_TIME;

#load "properties.jai";
#load "world.jai";
#load "collision.jai";
#load "collider.jai";
#load "raycast.jai";
#load "raycast_simple.jai";
#load "shape.jai";
#load "body.jai";
#load "update.jai";
#load "derive.jai";
#load "overlap.jai";
#load "convex.jai";
#load "config.jai";
#load "friction.jai";
#load "collision_broad_phase.jai";
#load "collision_narrow_phase.jai";

#scope_module

// Copyright (c) 2026 Trace Myers
// Licensed under the MIT License. See LICENSE file in the project root for license information.
